/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import Diem.Diem3D;
import Hinh2D.Ve2D;
import Hinh3D.HinhHopCN;
import Hinh3D.HinhChop;
import java.awt.Graphics;
import java.awt.Point;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import Hinh3D.Ve3D;
import java.awt.Color;
/**
 *
 * @author ADMIN
 */
public class Menu_app_3D extends javax.swing.JPanel {

    private  int WIDTH3D;
    private  int HEIGHT3D;
    private  Point root3D;
   
    boolean isDrew = false;
    boolean isDrewOxy = false;
    boolean isDrewGrib = false;
    private BufferedImage originImage3D,img;
 
    private BufferedImage img3D; 
    private boolean isRectangular = true;
    private boolean isHinhChop = true;
    
    private int ratioCar = 100;
    private String path3D = "./src/Image/img3d.jpg";
    private Diem3D truc;
   
    
    /**
     * Creates new form Menu_app
     */
    public Menu_app_3D() {
        initComponents();
        
        WIDTH3D = 1000;
        HEIGHT3D =700;
        originImage3D = readFileBufferedImage(path3D);
        img3D = copyImage(originImage3D);
       
        root3D = new Point(WIDTH3D / 5 * 2 - 1, HEIGHT3D / 2 - 1);
          setIcon(img3D, jlb_3D);
          setIcon(img3D, jlbHinhChop);
          //drawOxyz(WIDTH3D, HEIGHT3D);
          
        /// set cứng điểm gốc A trùng O
         
        
        
    }

     private BufferedImage readFileBufferedImage(String path) {
        try {
            return ImageIO.read(new File(path));
        } catch (IOException ex) {
            
        }
        return null;
    }
      public void resetInforLable() {
        jlbA.setText("");
        jlbB.setText("");
        jlbC.setText("");
        jlbD.setText("");
        jlbE.setText("");
        jlbF.setText("");
        jlbG.setText("");
        jlbH.setText("");
    }

   

    public void positionVisible3D(boolean isVisible) {
        jlbG.setVisible(isVisible);
        jlbH.setVisible(isVisible);
    }

     private void setIcon(BufferedImage img, JLabel lbl) {
        lbl.setIcon(new ImageIcon(img));
    }
     public BufferedImage copyImage(BufferedImage image) {
        BufferedImage temp = new BufferedImage(image.getWidth(), image.getHeight(),
                BufferedImage.TYPE_INT_RGB);
        Graphics g = temp.getGraphics();
        g.drawImage(image, 0, 0, image.getWidth(), image.getHeight(), null);
        return temp;
    }

    public BufferedImage drawOxyz(int WIDTH, int HEIGHT){
        //draw Ox
        Point dauOx = new Point(WIDTH/5*2 - 1, HEIGHT/2 - 1);
        Point cuoiOx = new Point(WIDTH - 1, HEIGHT/2 - 1);
        img = new Ve2D(img).drawLine(dauOx, cuoiOx, Color.BLACK);
        //draw Oy
        Point dauOy = new Point(WIDTH/5*2 - 1, 0);
        Point cuoiOy = new Point(WIDTH/5*2 - 1, HEIGHT/2 - 1);
        img = new Ve2D(img).drawLine(dauOy, cuoiOy, Color.BLACK);
        //draw Oz
        Point dauOz = new Point(WIDTH/5*2 - 1, HEIGHT/2 - 1);
        Point cuoiOz = new Point(WIDTH/5*2 - HEIGHT/2 - 1, HEIGHT - 1);
        img = new Ve2D(img).drawLine(dauOz, cuoiOz, Color.BLACK);
        //
        
        return img;
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel_3D = new javax.swing.JPanel();
        jlb_3D = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jlbHCN = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jlbA = new javax.swing.JLabel();
        jlbE = new javax.swing.JLabel();
        jlbB = new javax.swing.JLabel();
        jlbC = new javax.swing.JLabel();
        jlbF = new javax.swing.JLabel();
        jlbG = new javax.swing.JLabel();
        jlbD = new javax.swing.JLabel();
        jlbH = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jlbW = new javax.swing.JLabel();
        jlbL = new javax.swing.JLabel();
        txtX = new javax.swing.JTextField();
        txtW = new javax.swing.JTextField();
        txtY = new javax.swing.JTextField();
        txtZ = new javax.swing.JTextField();
        btnDraw = new javax.swing.JButton();
        txtL = new javax.swing.JTextField();
        txtH = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jlbHinhChop = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jlbA1 = new javax.swing.JLabel();
        jlbE1 = new javax.swing.JLabel();
        jlbB1 = new javax.swing.JLabel();
        jlbC1 = new javax.swing.JLabel();
        jlbF1 = new javax.swing.JLabel();
        jlbG1 = new javax.swing.JLabel();
        jlbD1 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jlbW1 = new javax.swing.JLabel();
        txtX1 = new javax.swing.JTextField();
        txtW1 = new javax.swing.JTextField();
        txtY1 = new javax.swing.JTextField();
        txtZ1 = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jlbHC = new javax.swing.JLabel();
        btnHinhChop = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtH1 = new javax.swing.JTextField();

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jPanel_3D.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel_3DLayout = new javax.swing.GroupLayout(jPanel_3D);
        jPanel_3D.setLayout(jPanel_3DLayout);
        jPanel_3DLayout.setHorizontalGroup(
            jPanel_3DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_3DLayout.createSequentialGroup()
                .addComponent(jlb_3D, javax.swing.GroupLayout.PREFERRED_SIZE, 984, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 15, Short.MAX_VALUE))
        );
        jPanel_3DLayout.setVerticalGroup(
            jPanel_3DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlb_3D, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(0, 153, 153));

        jPanel5.setBackground(new java.awt.Color(0, 153, 153));

        jlbHCN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbHCN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/hcn.png"))); // NOI18N
        jlbHCN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbHCNMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbHCN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(jlbHCN, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(204, 204, 255));

        jlbA.setBorder(new javax.swing.border.MatteBorder(null));

        jlbE.setBorder(new javax.swing.border.MatteBorder(null));

        jlbB.setBorder(new javax.swing.border.MatteBorder(null));

        jlbC.setBorder(new javax.swing.border.MatteBorder(null));

        jlbF.setBorder(new javax.swing.border.MatteBorder(null));

        jlbG.setBorder(new javax.swing.border.MatteBorder(null));

        jlbD.setBorder(new javax.swing.border.MatteBorder(null));

        jlbH.setBorder(new javax.swing.border.MatteBorder(null));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jlbA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(55, 55, 55)
                        .addComponent(jlbE, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlbD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlbB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlbC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(57, 57, 57)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jlbF, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jlbG, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jlbH, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlbA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlbE, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbB, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlbC, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(jlbG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlbD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlbH, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE))
                .addGap(21, 21, 21))
        );

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Xgoc");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Cao");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Ygoc");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Zgoc");

        jlbW.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlbW.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbW.setText("Dài");

        jlbL.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlbL.setText("Rộng");

        txtX.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtX.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtX.setText("0");

        txtW.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtW.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtY.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtY.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtY.setText("0");

        txtZ.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtZ.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtZ.setText("0");

        btnDraw.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDraw.setText("Vẽ Hình Hộp CN");
        btnDraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDrawActionPerformed(evt);
            }
        });

        txtL.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtL.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtH.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtH.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                                .addComponent(txtX, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtY, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                    .addComponent(txtZ))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jlbL)
                                .addGap(18, 18, 18)
                                .addComponent(txtL, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtW, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtH, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbW)
                    .addComponent(jLabel12))
                .addContainerGap(130, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDraw, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(txtH))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jlbW)
                    .addComponent(txtW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jlbL)
                    .addComponent(txtZ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtL))
                .addGap(67, 67, 67)
                .addComponent(btnDraw)
                .addGap(83, 83, 83))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_3D, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_3D, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("HÌNH HỘP CN", jPanel2);

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));

        jPanel7.setBackground(new java.awt.Color(204, 204, 255));

        jlbA1.setBorder(new javax.swing.border.MatteBorder(null));

        jlbE1.setBorder(new javax.swing.border.MatteBorder(null));

        jlbB1.setBorder(new javax.swing.border.MatteBorder(null));

        jlbC1.setBorder(new javax.swing.border.MatteBorder(null));

        jlbF1.setBorder(new javax.swing.border.MatteBorder(null));

        jlbG1.setBorder(new javax.swing.border.MatteBorder(null));

        jlbD1.setBorder(new javax.swing.border.MatteBorder(null));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jlbA1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                        .addComponent(jlbE1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jlbD1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(jlbC1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlbB1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbF1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlbG1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlbA1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlbE1, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbB1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbF1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlbC1, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(jlbG1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlbD1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Ygoc");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Zgoc");

        jlbW1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlbW1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbW1.setText("Rộng");

        txtX1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtX1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtX1.setText("0");

        txtW1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtW1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtY1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtY1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtY1.setText("0");

        txtZ1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtZ1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtZ1.setText("0");

        jPanel8.setBackground(new java.awt.Color(0, 153, 153));

        jlbHC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbHC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/hc.png"))); // NOI18N
        jlbHC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbHCMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbHC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbHC, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnHinhChop.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnHinhChop.setText("Vẽ Hình Chóp");
        btnHinhChop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHinhChopActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Xgoc");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Cao");

        txtH1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtH1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(btnHinhChop, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtX1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel16)
                                            .addComponent(jLabel15))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtY1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtZ1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jlbW1)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtW1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel18)
                                        .addGap(28, 28, 28)
                                        .addComponent(txtH1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(20, 20, 20))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel17)
                        .addComponent(txtX1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel18)
                        .addComponent(txtH1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jlbW1)
                    .addComponent(txtW1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtY1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtZ1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addComponent(btnHinhChop)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbHinhChop, javax.swing.GroupLayout.PREFERRED_SIZE, 1027, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlbHinhChop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("HÌNH CHÓP", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDrawActionPerformed
        int x = 0, y = 0, z = 0, h = 0, w = 0, l = 0, tile =5;
        if (isRectangular) {
            // get value
         try {
            x = Integer.parseInt(txtX.getText()) * tile ;
            y = Integer.parseInt(txtY.getText()) * tile ;
            z = Integer.parseInt(txtZ.getText()) * tile ;
                l = Integer.parseInt(txtL.getText()) * tile ;
                h = Integer.parseInt(txtH.getText()) * tile ;
                w = Integer.parseInt(txtW.getText()) * tile ;
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(jPanel2, "Nhập Sai");
                return;
            }
            //draw
            Diem3D p3D = new Diem3D(x, y, z);
            img3D = new HinhHopCN(p3D, l, w, h, img3D, root3D).Ve();
            //show info
            Diem3D p3d;
            p3d = new HinhHopCN(p3D, l, w, h, img3D, root3D).getViTri3D("A");
            jlbA.setText("A(" + p3d.getX() / tile  + ", " + p3d.getY() / tile  + ", " + p3d.getZ() / tile + ")");
            p3d = new HinhHopCN(p3D, l, w, h, img3D, root3D).getViTri3D("B");
            jlbB.setText("B(" + p3d.getX() / tile  + ", " + p3d.getY() / tile  + ", " + p3d.getZ() / tile  + ")");
            p3d = new HinhHopCN(p3D, l, w, h, img3D, root3D).getViTri3D("C");
            jlbC.setText("C(" + p3d.getX() / tile  + ", " + p3d.getY() / tile  + ", " + p3d.getZ() / tile  + ")");
            p3d = new HinhHopCN(p3D, l, w, h, img3D, root3D).getViTri3D("D");
            jlbD.setText("D(" + p3d.getX() / tile  + ", " + p3d.getY() / tile  + ", " + p3d.getZ() / tile  + ")");
            p3d = new HinhHopCN(p3D, l, w, h, img3D, root3D).getViTri3D("E");
            jlbE.setText("E(" + p3d.getX() / tile  + ", " + p3d.getY() / tile  + ", " + p3d.getZ() / tile  + ")");
            p3d = new HinhHopCN(p3D, l, w, h, img3D, root3D).getViTri3D("F");
            jlbF.setText("F(" + p3d.getX() / tile  + ", " + p3d.getY() / tile  + ", " + p3d.getZ() / tile  + ")");
            p3d = new HinhHopCN(p3D, l, w, h, img3D, root3D).getViTri3D("G");
            jlbG.setText("G(" + p3d.getX() / tile  + ", " + p3d.getY() / tile  + ", " + p3d.getZ() / tile  + ")");
            p3d = new HinhHopCN(p3D, l, w, h, img3D, root3D).getViTri3D("H");
            jlbH.setText("H(" + p3d.getX() / tile  + ", " + p3d.getY() / tile  + ", " + p3d.getZ() / tile  + ")");
        }
        //draw on lbl3D
        //img3D= drawOxyz(WIDTH3D, HEIGHT3D);
        setIcon(img3D, jlb_3D);

        img3D = copyImage(originImage3D);

    }//GEN-LAST:event_btnDrawActionPerformed

    private void jlbHCNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbHCNMouseClicked
        btnDraw.setText("Draw Rect");
        isRectangular = true;
        jlbW.setText("W");
        jlbL.setVisible(true);
        txtL.setVisible(true);
        positionVisible3D(true);
        resetInforLable();
    }//GEN-LAST:event_jlbHCNMouseClicked

    private void jlbHCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbHCMouseClicked
        btnDraw.setText("Draw SquarePyramid");
        isRectangular = false;
        jlbW.setText("R");
        jlbL.setVisible(false);
        txtL.setVisible(false);
        positionVisible3D(false);
        resetInforLable();
    }//GEN-LAST:event_jlbHCMouseClicked

    private void btnHinhChopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHinhChopActionPerformed
        int x = 0, y = 0, z = 0, h = 0, w = 0, l = 0, tile =5;
                
        if (isHinhChop) {
            // get value
           
            try {
               x = Integer.parseInt(txtX1.getText()) * tile;
               y = Integer.parseInt(txtY1.getText()) * tile;
               z = Integer.parseInt(txtZ1.getText()) * tile;
              
                w = Integer.parseInt(txtH1.getText()) * tile;
                h = Integer.parseInt(txtW1.getText()) * tile;
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(jPanel1, "Nhập Sai!");
                return;
            }
            //draw
            Diem3D p3D = new Diem3D(x, y, z);
            img3D = new HinhChop(p3D, h, w, img3D, root3D).Ve();
            //show infor
            
            //show infor
            Diem3D p3d;
            jlbA1.setText("A(" + x/tile + ", " + y/tile + ", " + z/tile + ")");
            p3d = new HinhChop(p3D, h, w, img3D, root3D).getViTri3D("B");
            jlbB1.setText("B(" + p3d.getX() / tile + ", " + p3d.getY() / tile
                    + ", " + p3d.getZ() / tile + ")");
            p3d = new HinhChop(p3D, h, w, img3D, root3D).getViTri3D("C");
            jlbC1.setText("C(" + p3d.getX() / tile + ", " + p3d.getY() / tile
                    + ", " + p3d.getZ() / tile + ")");
            p3d = new HinhChop(p3D, h, w, img3D, root3D).getViTri3D("D");
            jlbD1.setText("D(" + p3d.getX() / tile + ", " + p3d.getY() / tile
                    + ", " + p3d.getZ() / tile + ")");
            p3d = new HinhChop(p3D, h, w, img3D, root3D).getViTri3D("O'");
            jlbE1.setText("O'(" + p3d.getX() / tile + ", " + p3d.getY() / tile
                    + ", " + p3d.getZ() / tile + ")");
            p3d = new HinhChop(p3D, h, w, img3D, root3D).getViTri3D("S");
            jlbF1.setText("S(" + p3d.getX() / tile + ", " + p3d.getY() / tile
                    + ", " + p3d.getZ() / tile+ ")");
        }
        //draw on lbl3D
         //img3D= drawOxyz(WIDTH3D, HEIGHT3D);
         setIcon(img3D, jlbHinhChop);

        img3D = copyImage(originImage3D);

    }//GEN-LAST:event_btnHinhChopActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDraw;
    private javax.swing.JButton btnHinhChop;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel_3D;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel jlbA;
    private javax.swing.JLabel jlbA1;
    private javax.swing.JLabel jlbB;
    private javax.swing.JLabel jlbB1;
    private javax.swing.JLabel jlbC;
    private javax.swing.JLabel jlbC1;
    private javax.swing.JLabel jlbD;
    private javax.swing.JLabel jlbD1;
    private javax.swing.JLabel jlbE;
    private javax.swing.JLabel jlbE1;
    private javax.swing.JLabel jlbF;
    private javax.swing.JLabel jlbF1;
    private javax.swing.JLabel jlbG;
    private javax.swing.JLabel jlbG1;
    private javax.swing.JLabel jlbH;
    private javax.swing.JLabel jlbHC;
    private javax.swing.JLabel jlbHCN;
    private javax.swing.JLabel jlbHinhChop;
    private javax.swing.JLabel jlbL;
    private javax.swing.JLabel jlbW;
    private javax.swing.JLabel jlbW1;
    private javax.swing.JLabel jlb_3D;
    private javax.swing.JTextField txtH;
    private javax.swing.JTextField txtH1;
    private javax.swing.JTextField txtL;
    private javax.swing.JTextField txtW;
    private javax.swing.JTextField txtW1;
    private javax.swing.JTextField txtX;
    private javax.swing.JTextField txtX1;
    private javax.swing.JTextField txtY;
    private javax.swing.JTextField txtY1;
    private javax.swing.JTextField txtZ;
    private javax.swing.JTextField txtZ1;
    // End of variables declaration//GEN-END:variables
}
